name: Neural Network Test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Tests
      run: |
        pytest test/nn-training-test.py
